### PR TITLE
Several features and a some cleanup

### PR DESCRIPTION
**Pull request by toy**
Main points:
1. no idle sleep while running
2. exit code depending on success
3. show elapsed time and ETA
4. fixed buffer size of 8MiB
5. aes 128 cbc on zeroes for much faster source of data without fixed patterns

### CODE REVIEW

**Comment by rentzsch** [comment]
Looks great, thanks so much for making stressdrive better!

Questions:
- What's wrong with EXIT_FAILURE on syscall fail?
- Have any hard data on how much faster AES is over pseudorandom?
- Did you do measurement on if the 8MB fixed size buffer is actually faster?

**Comment by toy** [comment]
Fair questions, I should've posted them from the start.

There is nothing wrong with using only `EXIT_FAILURE`, but two fail codes allow to differentiate complete run which failed from run during which something went really wrong.

To answer other two I've used a ram disk (fast io, so everything else is taking bigger part of time). Both my internal disks have block count which would lead to 8x speed scale, so I've created a 4000004k disk. And here is output:
- Using urandom

```
…
writing 100.0% (1000001 of 1000001) 00:03:07
…
reading 100.0% (1000001 of 1000001) 00:00:28
…
```
- use fixed buffer size of 8MiB

```
…
writing 100.0% (8000008 of 8000008) 00:02:41
…
reading 100.0% (8000008 of 8000008) 00:00:11
…
```
- use aes 128 cbc (old openssl without using AES-NI)

```
…
writing 100.0% (8000008 of 8000008) 00:00:33
…
reading 100.0% (8000008 of 8000008) 00:00:11
…
```
- same with latest openssl using AES-NI (it seems sha1 is also faster)

```
…
writing 100.0% (8000008 of 8000008) 00:00:14
…
reading 100.0% (8000008 of 8000008) 00:00:07
…
```

I understand that buffer size depends on the disk. I've selected 8MB as 512 \* 16384 (max speed scale in original version). In few tests I saw big improvement when increasing buffer size till 256-512KB, afterwards not so much. More proper way would be to dynamically find the best buffer size, but this would complicate the code a lot. Current way will at least not allow small buffer/low speed for disks with block count not divisible by big power of two.

**Comment by toy** [comment]
@rentzsch Did I answer all your questions?

**Comment by rentzsch** [comment]
@toy Sorry for my delay in responding.

Yes, you did a great job of answering all my questions. Very thorough. Thanks so much.

**Pull request merged**
